name: open_grid_emissions
channels:
  - defaults
  - conda-forge
dependencies:
  - black # development: code formatting
  - cvxopt
  - cvxpy=1.2.1 # used by gridemissions, newer version not working as of 12/12/2022
  - flake8 # development: linter
  - geopandas # used for pudl
  - ipykernel
  - notebook
  - numpy
  - openpyxl
  - pandas
  - pip
  - plotly
  - pyarrow
  - pygeos # used for pudl
  - pytest
  - python>=3.10,<3.11 # require 3.10.x for compatibility with pudl
  - python-snappy # used for pudl
  - qdldl-python=0.1.5=py310hf5e1058_2 # used for gridemissions, newer version not working as of 12/12/2022
  - requests>=2.28.1
  - seaborn # used by gridemissions
  - setuptools # used for pudl
  - sqlalchemy
  - sqlite # used for pudl
  - statsmodels

  - pip:
      #- --editable ../pudl #NOTE: this is for development use
      - git+https://github.com/catalyst-cooperative/pudl.git#egg=catalystcoop.pudl
      #- --editable ../gridemissions # NOTE: this is for development use
      - git+https://github.com/gailin-p/gridemissions#egg=gridemissions
