name: hourly_egrid
channels:
  - defaults
  - conda-forge
dependencies:
  - dask
  - black
  - flake8 # linter
  - ipykernel
  - matplotlib
  - missingno
  - notebook
  - numpy
  - openpyxl
  - pandas
  - pathlib
  - pip
  - plotly
  - pyarrow
  - python
  - requests
  - sqlalchemy
  - statsmodels
  - tabulate


  - setuptools # used for pudl
  - geopandas # used for pudl
  - pygeos  # used for pudl
  - python-snappy # used for pudl
  - sqlite # used for pudl

  - pip:
    #- --editable ../pudl #NOTE: this is for Greg's use for development
    - git+https://github.com/grgmiller/pudl.git@allocate_fuel#egg=catalystcoop.pudl
    # - --editable ../gridemissions # NOTE: for Gailin's development use 
    - git+https://github.com/gailin-p/gridemissions#egg=gridemissions